# -*- coding: utf-8 -*-
"""Hamming - Receptor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gkc72Qn8ybD2fVAS3Br_gWoZLK-EbE6i
"""

def hamming_receptor():
    trama_emisor = input("\nIngrese la trama codificada: ").strip()

    n = len(trama_emisor)
    if n < 3:  # Mínimo para 1 bit de datos + 2 de redundancia
        print("Error: Trama demasiado corta para contener código Hamming")
        return

    r = 0
    while 2 ** r < n + 1:
        r += 1

    ep = 0
    for i in range(r):
        m = 1 << i
        p = 0
        for j in range(n):
            if (j + 1) & m:
                p ^= int(trama_emisor[j])
        if p:
            ep += m

    if ep > n:
        print("Error no corregible")
        print(f"Trama recibida: {trama_emisor}")
        return

    if ep > 0:
        # Corregir el error
        trama_corregida = list(trama_emisor)
        error_index = ep - 1  # Convertir a índice base 0
        trama_corregida[error_index] = '1' if trama_corregida[error_index] == '0' else '0'
        trama_corregida = ''.join(trama_corregida)

        print(f"Error detectado en la posición {ep}")
        print(f"Trama recibida:  {trama_emisor}")
        print(f"Trama corregida: {trama_corregida}")
    else:
        print("✓ No se detectaron errores")
        print(f"Trama recibida: {trama_emisor}")
        trama_corregida = trama_emisor

    original = []
    j = 1
    skip = {2 ** i for i in range(r)}

    for i in range(n):
        if (i + 1) not in skip:
            original.append(trama_corregida[i])

    print(f"\nDatos originales: {''.join(original)}")


if __name__ == "__main__":
    hamming_receptor()3